package:
    type:           yii2-extension
    name:           yii2-yandex-metrika
    title:          Yandex.Metrika counter for Yii2 applications
    headline:       Yii2 Yandex.Metrika
    keywords:       yii2, yandex, metrika
    description:    |
        Provides really easy adding [Yandex.Metrika] counter to site.
        Even easier then adding a widget into site layout.

        Works by adding Behavior to the Application View.
        Behavior listens to [EVENT_END_BODY] and echos the counter script.

        [Yandex.Metrika]: https://metrika.yandex.ru
        [EVENT_END_BODY]: http://www.yiiframework.com/doc-2.0/yii-web-view.html#EVENT_END_BODY-detail
